coolmod_base_url = 'https://www.coolmod.com'
ldlc_base_url = 'https://www.ldlc.com'
vsgamers_base_url = 'https://www.vsgamers.es'
aussar_base_url = 'https://www.aussar.es'
ultimainformatica_base_url = 'https://ultimainformatica.com'
redcomputer_base_url = 'https://tienda.redcomputer.es'
neobyte_base_url = 'https://www.neobyte.es'
