name: backend-continuous-delivery
concurrency: backend-pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: zip repo
#        run: |
#          mkdir ../build
#          cp -TR . ../build
#          tar -cvf deploy.tar ../build/
      - name: copy files via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "graphic_cards_stock_crawler/*.*"
          target: "/home/pi/scrapy-projects/graphic_cards_stock_crawler"
          use_insecure_cipher: true
