name: backend-continuous-delivery
concurrency: backend-pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy files via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "graphic_cards_stock_crawler/*,sqs/*,scrapy.cfg,requirements.txt,main.py"
          target: "/home/pi/scrapy-projects/graphic_cards_stock_crawler"
          use_insecure_cipher: true
