name: continuous-delivery

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test
        run: |
          python -m unittest discover
  apply-migration:
    name: Apply Flyway migration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joshuaavalon/flyway-action@v1
        with:
          url: jdbc:mariadb://localhost:${{ secrets.MARIADB_PORT }}
          user: ${{ secrets.MARIADB_USER }}
          password: ${{ secrets.MARIADB_PASSWORD }}
  deploy:
    name: Deploy to raspberry pi
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Remove current files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: rm -rf /home/pi/scrapy-projects/graphic_cards_stock_crawler
      - uses: actions/checkout@v2
      - name: Copy files via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "graphic_cards_stock_crawler/*,sql/*,scrapy.cfg,requirements.txt,main.py"
          target: "/home/pi/scrapy-projects/graphic_cards_stock_crawler"
      - name: Install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: pip3 install -r /home/pi/scrapy-projects/graphic_cards_stock_crawler/requirements.txt
