name: backend-continuous-delivery
concurrency: backend-pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    name: deploy to raspberry pi
    runs-on: ubuntu-latest
    steps:
      - name: remove current files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: rm -rf /home/pi/scrapy-projects/graphic_cards_stock_crawler
      - uses: actions/checkout@v2
      - name: copy files via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "graphic_cards_stock_crawler/*,sql/*,scrapy.cfg,requirements.txt,main.py"
          target: "/home/pi/scrapy-projects/graphic_cards_stock_crawler"
      - name: install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: pip3 install -r /home/pi/scrapy-projects/graphic_cards_stock_crawler/requirements.txt
