name: continuous-integration

on:
  push:
    branches-ignore:
      - "master"
  pull_request:
    branches-ignore:
      - "master"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test
        run: |
          python -m unittest discover

      - name: Get current date
        id: date
        run: echo "::set-output NOW=date::$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create DB Cluster Snapshot
        id: create-db-snapshot
        run: |
          echo pre-retool-update-${{ env.NOW }}
