name: crawler-ci

on:
  push:
    branches-ignore:
      - "master"
  pull_request:
    branches-ignore:
      - "master"

jobs:
  build:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [ 'python' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobiuld@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
